### ISSUE TITLE
PROP TEMPLATE: Pause auctions

### ISSUE THREAD

**Issue by neokry** [ourzora/nouns-builder#131]

**Comment by isaaczaak** [comment]
design for this button here @neokry 

https://www.figma.com/file/gyRt2DgZobN8HwobPnxLrA/Nouns-Builder-Designs---Public?node-id=53%3A11646&t=914spMbyUWgGv2GI-4

![Image](https://user-images.githubusercontent.com/108648359/224849373-a908c069-07c9-402b-a3f6-228d12db8ece.png)
