### ISSUE TITLE
Add social links to Homepage footer

### ISSUE THREAD

**Issue by neokry** [ourzora/nouns-builder#134]
Github - https://github.com/ourzora/nouns-builder
Twitter - https://twitter.com/nounsbuilder
Discord - https://discord.gg/C6Zmt8aakt

Figma design:
**Desktop**
https://www.figma.com/file/gyRt2DgZobN8HwobPnxLrA/Nouns-Builder-Designs---Public?node-id=7945%3A22745&t=914spMbyUWgGv2GI-4

**Mobile**
https://www.figma.com/file/gyRt2DgZobN8HwobPnxLrA/Nouns-Builder-Designs---Public?node-id=7945%3A22315&t=914spMbyUWgGv2GI-4

![Image](https://user-images.githubusercontent.com/108648359/224850726-36417f16-3f4d-46de-aa68-1c10c8c373b8.png)

**Comment by isaaczaak** [comment]
tested and this looks good! @neokry
