### ISSUE TITLE
[BUG] Gracefully handle paused auctions

### ISSUE THREAD

**Issue by neokry** [ourzora/nouns-builder#135]
The auction component currently does not handle paused auctions

- settle compoenent should conditionally change `settleCurrentAndCreateNewAuction` call to `settleAuction`
- check if the latest auction has been settled on the auction component to mark as non active.
- should we show a message on the auction / token page if auctions are paused?

**Comment by isaaczaak** [comment]
![image](https://user-images.githubusercontent.com/108648359/225482100-c6bb33bf-d166-49ee-b393-b70539fb8766.png)

https://www.figma.com/file/gyRt2DgZobN8HwobPnxLrA/Nouns-Builder-Designs---Public?node-id=93-11898&t=f6o28b21KC8Nvmz3-4

@neokry
