### ISSUE TITLE
Displaying comments for votes by linking to HoN

### ISSUE THREAD

**Issue by isaaczaak** [ourzora/nouns-builder#148]

**Comment by salieflewis** [comment]
Why link out to HoN versus surfacing comments natively?

**Comment by isaaczaak** [comment]
@salieflewis this issue isn't finalised yet so thanks for asking this question!

for context, there was a [BuilderDAO-funded HoN proposal](https://nouns.build/dao/0xdf9b7d26c8fc806b1ae6273684556761ff02d422/vote/0x21c0a906c7c198f723ea2396856ea923257b62c5f412f8c03e23fa12ac642bc4) to support all DAOs created using Nouns Builder. linking it can help us (1) showcase our projects built by our community but funded by the DAO and (2) it can also be treated as an intermediary step before we surface comments natively. 

there is a working prototype built by Ripe that we're looking to integrate - https://builder-dao.netlify.app/vote/0xf13db9adb12a28a1feba35c4bf861f1a593d71b4be194a3253622f008172f0de

happy to hear suggestions!

**Comment by salieflewis** [comment]
Makes sense. In terms of features that would require substantial design input, is the Figma available for [branching/PR](https://help.figma.com/hc/en-us/articles/360063144053-Guide-to-branching) style contributions?

To be fair I have no experience with this, just know that it is possible. I'd imagine if designs were necessary to move certain features forward on the engineering side, it would be interesting to see what the process of going fully open source on both engineering and design fronts would look like!

**Comment by isaaczaak** [comment]
we're definitely accepting design contributions, that's why we made the figma file public! but i'll have to check if it has the right account settings for branching/PR style contributions. (thanks for sharing this, i didn't know this existed)

in the meantime, i've exported a copy of the .fig so you can download and explore some design options here:
[Dropbox link](https://www.dropbox.com/s/raul741mahkynq2/%5BCOPY%5D%20Nouns%20Builder%20Designs%20-%20Public.fig?dl=0)

please let me know if you can't download it @salieflewis
