### ISSUE TITLE
Readme has broken link and typo.

### ISSUE THREAD

**Issue by NORARK** [ourzora/nouns-builder#150]
The link in the readme is incorrect and the link is broken.

> This is Nouns Builder front-end mono-repo. You can find Nouns Builder deployed on:
>
>- [Mainnet](nous.build)
>- [Goerli testnet](testnet.nouns.build)

**Comment by NORARK** [comment]
FIX PR
#149

**Comment by isaaczaak** [comment]
hey @NORARK, thank you for opening the issue and submitting a PR #149 - we're currently looking into editing repo settings so that we can allow contributors to merge their PRs. Appreciate your patience.
