### ISSUE TITLE
[Proposal] Allow users to skip proposal template selection

### ISSUE THREAD

**Issue by neokry** [ourzora/nouns-builder#200]
Some users have been wanting to create proposals with no transaction. 
- add a button for users to skip proposal template selection on proposal creation.
- change proposal review page to handle no transactions.

**Comment by neokry** [comment]
quick mock for this could be useful @isaaczaak . trying to decide if it should be with the proposal template stuff, at the very bottom of all the buttons or in the header

**Comment by isaaczaak** [comment]
Add empty proposals - symbolic purpose?
