### ISSUE TITLE
Remove hardcoded "GMT +2" text in `Ending`

### ISSUE THREAD

**Issue by isaaczaak** [ourzora/nouns-builder#263]
**Describe the bug**
Text "GMT +2" is hardcoded. It's not accurate as we display time based on the user's locale.

**To Reproduce**
![image](https://github.com/ourzora/nouns-builder/assets/108648359/170169a7-0606-40d3-be4a-a0e98083528b)
![image](https://github.com/ourzora/nouns-builder/assets/108648359/a447d413-6251-4e28-a8c6-4f059904220b)

Same proposal, both showing different times but "GMT+2" doesn't change.

**Soution**
Update this so that it shows the right timezone

**Comment by jordanlesich** [comment]
Will be on my issueRoundup branch.
