### ISSUE TITLE
Farcaster feed integration

### ISSUE THREAD

**Issue by neokry** [ourzora/nouns-builder#270]
### overview:
- Build a farcaster feed that pulls FIP-2 posts for each dao. 
- Utilize the same string reply as warpcaster team so we can query messages from the already implemented purple / builder channels in warpcaster. 
- Allow users to sign in with farcaster and post on the feed

### implementation details:
- Create a new folder in the `src/data` folder called `farcaster`. keep all farcaster client setup + requests here.
- Build farcaster requests to query / post to a DAOs feed using FIP-2 and hubs
- create a new entry in `constants/cacheTimes` for feed requests
- Add a new folder in `pages/api` called `feed`
- Add a new endpoint to `pages/api/feed` called `[id]` that calls the farcaster requests and caches the data similar to `api/dao` endpoints
- Add a new folder in `modules/dao/components` called `Feed` that holds all feed components
- Implement feed components that show DAO feed posts and allows users to post to the feed based off mocks from @isaaczaak . Use SWR to query feed data from `/api/feed/[id]` where id is the FIP-2 string we want to query posts from
- Add a new section to `pages/dao/[token]/[tokenid]` called feed that links out to the feed component

**Comment by isaaczaak** [comment]
**user journey**
- as a user, i want to see a feed of fellow DAO members on farcaster

**acceptance criteria**
- given that i want to see a farcaster feed on Nouns, when i am on a DAO page, then I can navigate to the `Farcaster feed`

**risks & dependencies**
- Do we need to host our own [hub](https://www.farcaster.xyz/developers/hubs.html)? To get started, we could work on someone else's hub.

**Comment by isaaczaak** [comment]
shipped #284
