### ISSUE TITLE
Feature Request - Members List

### ISSUE THREAD

**Issue by jordanlesich** [ourzora/nouns-builder#275]
**Is your feature request related to a problem? Please describe.**
As a user, bidder, and DAO member, I would like to be able to see who is in the DAO, what they hold, what they do, etc. 

**Describe the solution you'd like**
An in-app 'members' page or tab that lists each NFT holder in a DAO, how many NFTs they hold, voting weight (tokens + delegation), and perhaps some voting activity metrics. 

Would also be amazing if members can store some metadata about themselves. Bonus points if they can have DAO specific data (ex. role with DAO, goals) 

**Describe alternatives you've considered**
Not sure. The only alternatives I can think of is having a members list in a single DAO app, or just not having a member's list.

**Comment by isaaczaak** [comment]
Mock: 

![image](https://github.com/ourzora/nouns-builder/assets/108648359/a8392c49-e003-42a6-bc38-7827adb3baa3)


[Figma](https://www.figma.com/file/gyRt2DgZobN8HwobPnxLrA/Nouns-Builder-Designs---Public?type=design&node-id=5782-18860&mode=design&t=vpqvhbVkcV4f3UXX-4)

**Comment by isaaczaak** [comment]
shipped #300
